version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./logs/mysql:/var/log/mysql:cached
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
    networks:
      - php-network
  nginx:
    image: nginx:stable
    restart: on-failure
    volumes:
      - ./logs:/logs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - symfony-var:/usr/src/app/var
    ports:
      - '8001:80'
    networks:
      - php-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./logs:/logs
      - symfony-var:/usr/src/app/var
    restart: on-failure
    env_file:
      - .env
    networks:
      - php-network

networks:
  php-network:
    driver: bridge

volumes:
  symfony-var:
  mysql-data: